import React from 'react';
import RodapeInstitucional from './RodapeInstitucional';

const CSS = `
.lgt{min-height:100vh;background:#07101f;color:#f8fafc;font-family:Inter,Segoe UI,system-ui,sans-serif}.lgt *{box-sizing:border-box}.lgt .wrap{width:min(820px,calc(100% - 40px));margin:auto}.lgt .top{padding:24px 0;border-bottom:1px solid rgba(148,163,184,.18)}.lgt .brand{text-align:center;font-size:13px;font-weight:900;letter-spacing:.12em}.lgt .brand span{color:#22d3ee}.lgt main{padding:58px 0 76px}.lgt .eyebrow{display:inline-flex;padding:8px 13px;border:1px solid rgba(34,211,238,.35);border-radius:999px;color:#67e8f9;background:rgba(34,211,238,.08);font-size:12px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.lgt h1{font-size:clamp(32px,5vw,50px);line-height:1.05;letter-spacing:-.04em;margin:18px 0 12px}.lgt .intro{color:#a8b6cc;font-size:17px;line-height:1.6;margin:0 0 30px}.lgt .card{border:1px solid rgba(148,163,184,.2);background:rgba(15,23,42,.72);border-radius:18px;padding:26px;margin:14px 0}.lgt h2{font-size:20px;margin:0 0 10px}.lgt p,.lgt li{color:#c4d0e1;line-height:1.65;font-size:15px}.lgt ul{padding-left:22px;margin:10px 0 0}.lgt .back{display:inline-block;margin-top:24px;color:#67e8f9;font-weight:800;text-decoration:none}.lgt strong{color:#fff}
`;

export default function LandingTermosGratuitos() {
  return <div className="lgt"><style>{CSS}</style>
    <header className="top"><div className="wrap"><div className="brand">LBW <span>·</span> EDUCAÇÃO PELO TRABALHO</div></div></header>
    <main><div className="wrap">
      <span className="eyebrow">Cursos gratuitos LBW</span>
      <h1>Termos e condições dos treinamentos gratuitos</h1>
      <p className="intro">Estes termos explicam como funciona o acesso gratuito aos cursos, às análises estatísticas e aos recursos liberados pela plataforma LBW — Educação pelo Trabalho.<br /><small>Versão vigente: 25 de agosto de 2026.</small></p>

      <section className="card"><h2>1. O que está sendo oferecido</h2><p>O participante recebe acesso gratuito ao pacote indicado na página de inscrição. O pacote pode incluir videoaulas, exercícios, análises estatísticas, software LBW e o Mentor Israel digital, conforme o produto divulgado.</p></section>
      <section className="card"><h2>2. Validade do acesso</h2><p>Os acessos gratuitos desta campanha são válidos até <strong>31 de dezembro de 2026</strong>. A LBW poderá criar novas campanhas, alterar os produtos gratuitos ou encerrar uma campanha futura, sem retirar os acessos já utilizados dentro do período informado.</p></section>
      <section className="card"><h2>3. Requisitos para o certificado</h2><p>O certificado não é liberado apenas pelo cadastro. Para emitir o certificado, o aluno deverá cumprir todos os requisitos abaixo:</p><ul><li>assistir a pelo menos <strong>70% dos vídeos</strong> do curso;</li><li>realizar o teste de avaliação correspondente;</li><li>obter nota mínima de <strong>70% (7,0 em uma escala de 0 a 10)</strong>;</li><li>após a aprovação, responder à pergunta aberta e enviar um depoimento sobre a experiência na plataforma LBW.</li></ul><p>O envio do depoimento após a aprovação é obrigatório para a emissão do certificado gratuito.</p></section>
      <section className="card"><h2>4. Depoimento e divulgação</h2><p>O depoimento deve ser verdadeiro e pode ser positivo, negativo ou conter sugestões. Ao enviar o depoimento, o aluno autoriza a LBW a utilizá-lo para melhorar a plataforma e, quando houver autorização específica, para divulgação institucional.</p><p>Depois de receber o certificado, convidamos o aluno a publicar sua conquista no LinkedIn, mostrando o certificado e mencionando a LBW. Essa divulgação ajuda outras pessoas a conhecerem o treinamento; ela não substitui os requisitos técnicos de conclusão.</p></section>
      <section className="card"><h2>5. Uso responsável</h2><p>O acesso é individual e não deve ser compartilhado, vendido, copiado ou utilizado para distribuir os materiais da LBW. O aluno pode aplicar os conhecimentos e as análises em seus próprios estudos e projetos, respeitando a confidencialidade dos dados da sua organização.</p></section>
      <section className="card"><h2>6. Dados, comunicação e segurança</h2><p>Ao se cadastrar, o aluno autoriza a LBW a enviar mensagens periódicas relacionadas ao treinamento, ao seu acesso, à plataforma, à comunidade e a novas oportunidades educacionais. O aluno poderá ser convidado a participar de uma comunidade ou grupo de estudos no WhatsApp relacionado ao treinamento. A participação poderá ser recusada ou interrompida pelo aluno.</p><p>O aluno poderá solicitar a interrupção dessas comunicações periódicas pelos canais de contato da LBW; mensagens essenciais sobre acesso, segurança, alterações relevantes e certificação poderão continuar sendo enviadas.</p><p>O e-mail e o número de WhatsApp não serão vendidos nem divulgados a terceiros para fins comerciais. Eles serão utilizados para criar e administrar o acesso, enviar credenciais, avisos importantes, comunicações relacionadas ao treinamento, convites para a comunidade e melhorar a experiência na plataforma.</p><p>A LBW não visualiza nem tem acesso à senha pessoal do aluno. A senha é tratada pelo serviço de autenticação da plataforma. Em caso de perda, o aluno deverá utilizar o procedimento de recuperação de senha.</p><p>Para proteger a comunidade, a LBW poderá controlar, moderar, organizar, restringir ou remover informações, publicações e interações que violem as regras da comunidade, prejudiquem outros participantes ou exponham dados confidenciais. Os dados e interações fornecidos na plataforma poderão ser analisados para corrigir problemas, desenvolver recursos e melhorar o aplicativo, respeitando a Política de Privacidade e a legislação aplicável.</p></section>
      <section className="card"><h2>7. LGPD e confidencialidade</h2><p>O tratamento dos dados pessoais segue a <strong>Lei Geral de Proteção de Dados Pessoais (LGPD — Lei nº 13.709/2018)</strong>. A LBW coleta e utiliza apenas os dados necessários para criar e manter o acesso, enviar comunicações relacionadas ao treinamento, acompanhar a evolução educacional, emitir certificados, prestar suporte, proteger a comunidade e melhorar a plataforma.</p><p>A LBW adota medidas razoáveis de segurança e não vende nem divulga o e-mail do aluno para terceiros. Quando necessário para operar o serviço, dados poderão ser tratados por fornecedores técnicos, como autenticação, hospedagem e envio de mensagens, sempre dentro da finalidade do serviço e das obrigações legais aplicáveis.</p><p>O aluno poderá solicitar informações sobre o uso de seus dados, correção, atualização, eliminação quando cabível, revogação de consentimentos e interrupção de comunicações periódicas, pelos canais de contato da LBW. Alguns registros poderão ser mantidos quando necessários para cumprir obrigações legais, preservar a segurança, resolver disputas ou comprovar a emissão de certificados.</p><p>A comunidade é um ambiente compartilhado. O aluno não deve publicar senhas, dados pessoais sensíveis, informações de clientes, documentos internos ou qualquer informação confidencial de sua empresa. Cada participante é responsável pelo conteúdo que publicar, e a LBW poderá moderar, restringir ou remover publicações que violem estas regras.</p></section>
      <section className="card"><h2>8. Aceite</h2><p>Ao marcar a caixa de aceite na página de inscrição, o participante confirma que leu e concorda com estes termos e condições, inclusive com o tratamento de dados descrito nesta seção e na Política de Privacidade.</p></section>
      <a className="back" href="/" onClick={(event) => { event.preventDefault(); window.history.length > 1 ? window.history.back() : window.location.assign('/'); }}>← Voltar para o cadastro gratuito</a>
    </div></main><RodapeInstitucional />
  </div>;
}
